apiVersion: sso.apps.tanzu.vmware.com/v1alpha1
kind: ClientRegistration
metadata:
  name: client-credentials-client-registration
  namespace: dev
spec:
  authServerSelector:
    matchLabels:
      env: production
      name: auth0-authserver
  authorizationGrantTypes:
    - client_credentials
    - refresh_token
  clientAuthenticationMethod: client_secret_basic
  scopes:
    - name: openid
    - name: developer.read
    - name: developer.write